version: '3'

networks:
  simdiklat:

services:
  nginx: 
    image: nginx:stable-alpine
    container_name: nginx
    ports: 
      - "8087:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - simdiklat

  mysql:
    image: mysql:latest
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports: 
    - "63306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: simdiklat
      MYSQL_USER: rahmat
      MYSQL_PASSWORD: efotoadmin
      MYSQL_ROOT_PASSWORD: efotoadmin
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
     - simdiklat

  php:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: php
    volumes:
        - ./src:/var/www/html
    ports:
        - "9000:9000"
    networks:
      - simdiklat

  redis:
    image: redis:6.2-alpine
    restart: unless-stopped
    ports:
      - '7379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes: 
      - ./redis:/data
    networks:
      - simdiklat